export const BUILD_MOOD = 'prod';

export const ENV_CONFIGS = {
  default: {
    dev: {
      idApiBaseUrl: 'https://devid.trovahealth.app/',
      providerApiBaseUrl: 'https://devproviderapi.trovahealth.app/api/v1/',
      practiceApiBaseUrl: 'https://devpracticeapi.trovahealth.app/api/v1/',
      billingApiBaseUrl: 'https://devbilling.trovahealth.app/api/v1/',
      schedulingApiBaseUrl: 'https://devschedulingapi.trovahealth.app/api/v1/',
      patientApiBaseUrl: 'https://devpatientapi.trovahealth.app/api/v1/',
      personalizedBaseUrl: 'YOUR_PERSONALIZED_BASE_DOMAIN',
      nylasApiUrl: 'https://api.eu.nylas.com',
      forgotPasswordUrl: 'https://devid.trovahealth.app/forgot-password-1',
      showEruda: false,
      notesApiBaseUrl: 'https://devnotesapi.trovahealth.app//api/v1/',
      analyticsApiBaseUrl: 'https://devanalyticsapi.trovahealth.app/api/v1/',
    },
    prod: {
      idApiBaseUrl: 'https://id.trovahealth.app/',
      providerApiBaseUrl: 'https://providerapi.trovahealth.app/api/v1/',
      practiceApiBaseUrl: 'https://practiceapi.trovahealth.app/api/v1/',
      billingApiBaseUrl: 'https://billing.trovahealth.app/api/v1/',
      schedulingApiBaseUrl: 'https://schedulingapi.trovahealth.app/api/v1/',
      patientApiBaseUrl: 'https://patientapi.trovahealth.app/api/v1/',
      personalizedBaseUrl: 'YOUR_PERSONALIZED_BASE_DOMAIN',
      nylasApiUrl: 'https://api.eu.nylas.com',
      forgotPasswordUrl: 'https://id.trovahealth.app/forgot-password-1',
      showEruda: false,
      notesApiBaseUrl: 'https://notesapi.trovahealth.app/api/v1/',
      analyticsApiBaseUrl: 'https://analyticsapi.trovahealth.app/api/v1/',
    },
    qa: {
      idApiBaseUrl: 'https://qaid.trovahealth.app/',
      providerApiBaseUrl: 'https://qaproviderapi.trovahealth.app/api/v1/',
      practiceApiBaseUrl: 'https://qapracticeapi.trovahealth.app/api/v1/',
      billingApiBaseUrl: 'https://qabilling.trovahealth.app/api/v1/',
      schedulingApiBaseUrl: 'https://qaschedulingapi.trovahealth.app/api/v1/',
      patientApiBaseUrl: 'https://qapatientapi.trovahealth.app/api/v1/',
      personalizedBaseUrl: 'YOUR_PERSONALIZED_BASE_DOMAIN',
      nylasApiUrl: 'https://api.eu.nylas.com',
      forgotPasswordUrl: 'https://qaid.trovahealth.app/forgot-password-1',
      showEruda: false,
      notesApiBaseUrl: 'https://qanotesapi.trovahealth.app//api/v1/',
      analyticsApiBaseUrl: 'https://qaanalyticsapi.trovahealth.app/api/v1/',
    },
  },
  br: {
    dev: {
      idApiBaseUrl: 'https://devid.trovahealth.com.br/',
      providerApiBaseUrl: 'https://devproviderapi.trovahealth.com.br/api/v1/',
      practiceApiBaseUrl: 'https://devpracticeapi.trovahealth.com.br/api/v1/',
      billingApiBaseUrl: 'https://devbilling.trovahealth.com.br/api/v1/',
      schedulingApiBaseUrl: 'https://devschedulingapi.trovahealth.com.br/api/v1/',
      patientApiBaseUrl: 'https://devpatientapi.trovahealth.com.br/api/v1/',
      personalizedBaseUrl: '',
      nylasApiUrl: 'https://api.eu.nylas.com',
      forgotPasswordUrl: 'https://devid.trovahealth.app/forgot-password-1',
      showEruda: false,
      notesApiBaseUrl: 'https://devnotesapi.trovahealth.com.br/api/v1/',
      analyticsApiBaseUrl: 'https://devanalyticsapi.trovahealth.com.br/api/v1/',
    },
    prod: {
      idApiBaseUrl: 'https://id.trovahealth.com.br/',
      providerApiBaseUrl: 'https://providerapi.trovahealth.com.br/api/v1/',
      practiceApiBaseUrl: 'https://practiceapi.trovahealth.com.br/api/v1/',
      billingApiBaseUrl: 'https://billing.trovahealth.com.br/api/v1/',
      schedulingApiBaseUrl: 'https://schedulingapi.trovahealth.com.br/api/v1/',
      patientApiBaseUrl: 'https://patientapi.trovahealth.com.br/api/v1/',
      personalizedBaseUrl: '',
      nylasApiUrl: 'https://api.eu.nylas.com',
      forgotPasswordUrl: 'https://id.trovahealth.app/forgot-password-1',
      showEruda: false,
      notesApiBaseUrl: 'https://notesapi.trovahealth.com.br/api/v1/',
      analyticsApiBaseUrl: 'https://analyticsapi.trovahealth.com.br/api/v1/',
    },
    qa: {
      idApiBaseUrl: 'https://id.trovahealth.com.br/',
      providerApiBaseUrl: 'https://qaproviderapi.trovahealth.com.br/api/v1/',
      practiceApiBaseUrl: 'https://qapracticeapi.trovahealth.com.br/api/v1/',
      billingApiBaseUrl: 'https://qabilling.trovahealth.com.br/api/v1/',
      schedulingApiBaseUrl: 'https://qaschedulingapi.trovahealth.com.br/api/v1/',
      patientApiBaseUrl: 'https://qapatientapi.trovahealth.com.br/api/v1/',
      personalizedBaseUrl: '',
      nylasApiUrl: 'https://api.eu.nylas.com',
      forgotPasswordUrl: 'https://qaid.trovahealth.app/forgot-password-1',
      showEruda: false,
      notesApiBaseUrl: 'https://qanotesapi.trovahealth.com.br/api/v1/',
      analyticsApiBaseUrl: 'https://qaanalyticsapi.trovahealth.com.br/api/v1/',
    },
  },
};
